[package]
name = "libp2p-lookup"
version = "0.4.0"
authors = ["Max Inden <mail@max-inden.de>"]
edition = "2018"
license = "MIT"
description = "Lookup a peer by its id."
repository = "https://github.com/mxinden/libp2p-lookup"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libp2p = { version = "0.42", default-features = false, features = ["dns-async-std", "noise", "tcp-async-io", "yamux", "identify", "kad", "ping", "mplex"] }
structopt = "0.3.26"
futures = "0.3.19"
env_logger = "0.9.0"
async-std = { version = "1.10.0", features = ["attributes"] }
ansi_term = "0.12.1"
