[package]
name = "libp2p-lookup"
version = "0.1.0"
authors = ["Max Inden <mail@max-inden.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libp2p = { version = "0.32", default-features = false, features = ["dns", "noise", "tcp-async-std", "yamux", "identify", "kad", "ping", "mplex"] }
structopt = "0.3.20"
futures = "0.3.8"
env_logger = "0.8.2"
async-std = { version = "1.8.0", features = ["attributes"] }
ansi_term = "0.12"
